[package]
name = "polars-rfft"
version = "0.1.1"
edition = "2021"

[lib]
name = "_polars_rfft"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.53", default-features = false, features = ["dtype-struct"] }
polars-core = { version = "0.53", features = ["dtype-struct"] }
polars-arrow = { version = "0.53" }
pyo3 = { version = "0.27", features = ["abi3-py39"] }
pyo3-polars = { version = "0.26", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
rustfft = "6"
num-complex = "0.4"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = 3
